FROM python:3.11-slim AS base
WORKDIR /app

FROM base AS deps
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM deps AS runner
COPY backend .
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["uvicorn", "app.api.main:api", "--host", "0.0.0.0", "--port", "8000"]
